"""initial schema

Revision ID: 5db743bafc2a
Revises: 
Create Date: 2026-05-23 12:45:26.437448
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '5db743bafc2a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES_WITH_UPDATED_AT = (
    'clinics',
    'audit_log',
    'broadcasts',
    'doctors',
    'failed_messages',
    'messages',
    'patients',
    'tests',
    'appointment_slots',
    'conversation_sessions',
    'recall_schedules',
    'reviews',
    'test_bookings',
    'appointments',
)

RLS_TABLES = (
    'patients',
    'appointments',
    'test_bookings',
    'conversation_sessions',
    'messages',
    'recall_schedules',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    op.execute("""
    CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """)
    op.create_table('clinics',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('clinic_type', sa.String(length=32), nullable=True),
    sa.Column('whatsapp_number', sa.Text(), nullable=False),
    sa.Column('owner_whatsapp', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('pincode', sa.Text(), nullable=True),
    sa.Column('google_place_id', sa.Text(), nullable=True),
    sa.Column('gbp_review_link', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('plan_active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("clinic_type IN ('gp','diagnostic','eye','dental','physio','other')", name='ck_clinics_clinic_type'),
    sa.CheckConstraint("plan IN ('starter','clinic','diagnostic','chain')", name='ck_clinics_plan'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_table('audit_log',
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('patient','owner','staff','system')", name='ck_audit_actor_type'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_clinic', 'audit_log', ['clinic_id', 'created_at'], unique=False)
    op.create_table('broadcasts',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','scheduled','sent','failed')", name='ck_broadcasts_status'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_clinic_id'), 'broadcasts', ['clinic_id'], unique=False)
    op.create_table('doctors',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('whatsapp_number', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_clinic_id'), 'doctors', ['clinic_id'], unique=False)
    op.create_table('failed_messages',
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_number', sa.Text(), nullable=True),
    sa.Column('wa_message_id', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wa_message_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound','outbound')", name='ck_messages_direction'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_index('idx_messages_clinic_number', 'messages', ['clinic_id', 'whatsapp_number', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_clinic_id'), 'messages', ['clinic_id'], unique=False)
    op.create_table('patients',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location_lat', sa.Numeric(), nullable=True),
    sa.Column('location_lng', sa.Numeric(), nullable=True),
    sa.Column('opt_in', sa.Boolean(), nullable=False),
    sa.Column('opt_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male','female','other') OR gender IS NULL", name='ck_patients_gender'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'whatsapp_number', name='uq_patients_clinic_whatsapp')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_table('tests',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_hindi', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('requires_fasting', sa.Boolean(), nullable=False),
    sa.Column('home_collection_available', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_clinic_id'), 'tests', ['clinic_id'], unique=False)
    op.create_table('appointment_slots',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('slot_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'doctor_id', 'slot_datetime', name='uq_slots_clinic_doctor_time')
    )
    op.create_index(op.f('ix_appointment_slots_clinic_id'), 'appointment_slots', ['clinic_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_number', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=True),
    sa.Column('step', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'whatsapp_number', name='uq_sessions_clinic_whatsapp')
    )
    op.create_index('idx_session_active', 'conversation_sessions', ['whatsapp_number', 'clinic_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_conversation_sessions_clinic_id'), 'conversation_sessions', ['clinic_id'], unique=False)
    op.create_table('recall_schedules',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','sent','responded','dismissed','snoozed')", name='ck_recalls_status'),
    sa.CheckConstraint("trigger_type IN ('annual_checkup','hba1c_quarterly','thyroid_6month','lipid_annual','followup','custom')", name='ck_recalls_trigger_type'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recall_pending', 'recall_schedules', ['trigger_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_recall_schedules_clinic_id'), 'recall_schedules', ['clinic_id'], unique=False)
    op.create_table('reviews',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.Text(), nullable=True),
    sa.Column('google_review_id', sa.Text(), nullable=True),
    sa.Column('draft_reply', sa.Text(), nullable=True),
    sa.Column('reply_approved', sa.Boolean(), nullable=False),
    sa.Column('reply_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('google','practo','justdial') OR source IS NULL", name='ck_reviews_source'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_clinic_id'), 'reviews', ['clinic_id'], unique=False)
    op.create_table('test_bookings',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('test_name', sa.Text(), nullable=False),
    sa.Column('booking_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('collection_address', sa.Text(), nullable=True),
    sa.Column('collection_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('collection_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('collection_slot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technician_name', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('report_file_path', sa.Text(), nullable=True),
    sa.Column('report_password', sa.Text(), nullable=True),
    sa.Column('report_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_status_notified', sa.Boolean(), nullable=False),
    sa.Column('fasting_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("booking_type IN ('walkin','home_collection')", name='ck_bookings_type'),
    sa.CheckConstraint("payment_status IN ('pending','paid','partial')", name='ck_bookings_payment'),
    sa.CheckConstraint("status IN ('booked','sample_collected','processing','report_ready','delivered','cancelled')", name='ck_bookings_status'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_bookings_status', 'test_bookings', ['clinic_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_test_bookings_clinic_id'), 'test_bookings', ['clinic_id'], unique=False)
    op.create_table('appointments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('appointment_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('appointment_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_1hr_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_24hr_sent', sa.Boolean(), nullable=False),
    sa.Column('review_request_sent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("appointment_type IN ('consultation','followup','walkin')", name='ck_appointments_type'),
    sa.CheckConstraint("status IN ('confirmed','cancelled','completed','no_show','rescheduled')", name='ck_appointments_status'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointments_clinic_date', 'appointments', ['clinic_id', 'appointment_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    for table_name in TABLES_WITH_UPDATED_AT:
        op.execute(f'ALTER TABLE {table_name} ALTER COLUMN id SET DEFAULT gen_random_uuid()')
        op.execute(
            f'CREATE TRIGGER {table_name}_updated_at '
            f'BEFORE UPDATE ON {table_name} '
            'FOR EACH ROW EXECUTE FUNCTION set_updated_at()'
        )

    for table_name in RLS_TABLES:
        op.execute(f'ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY {table_name}_clinic_isolation ON {table_name} '
            "USING (clinic_id = current_setting('app.clinic_id', true)::uuid)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in RLS_TABLES:
        op.execute(f'DROP POLICY IF EXISTS {table_name}_clinic_isolation ON {table_name}')

    for table_name in TABLES_WITH_UPDATED_AT:
        op.execute(f'DROP TRIGGER IF EXISTS {table_name}_updated_at ON {table_name}')

    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_index('idx_appointments_clinic_date', table_name='appointments', postgresql_where='deleted_at IS NULL')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_test_bookings_clinic_id'), table_name='test_bookings')
    op.drop_index('idx_test_bookings_status', table_name='test_bookings', postgresql_where='deleted_at IS NULL')
    op.drop_table('test_bookings')
    op.drop_index(op.f('ix_reviews_clinic_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_recall_schedules_clinic_id'), table_name='recall_schedules')
    op.drop_index('idx_recall_pending', table_name='recall_schedules', postgresql_where="status = 'pending'")
    op.drop_table('recall_schedules')
    op.drop_index(op.f('ix_conversation_sessions_clinic_id'), table_name='conversation_sessions')
    op.drop_index('idx_session_active', table_name='conversation_sessions', postgresql_where='is_active = true')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_appointment_slots_clinic_id'), table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_index(op.f('ix_tests_clinic_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_messages_clinic_id'), table_name='messages')
    op.drop_index('idx_messages_clinic_number', table_name='messages')
    op.drop_table('messages')
    op.drop_table('failed_messages')
    op.drop_index(op.f('ix_doctors_clinic_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_broadcasts_clinic_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index('idx_audit_clinic', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('clinics')
    op.execute('DROP FUNCTION IF EXISTS set_updated_at()')
    # ### end Alembic commands ###

