from app.templates.hinglish import (
    CONSENT_ACCEPTED,
    CONSENT_DECLINED,
    CONSENT_PROMPT,
    HOME_COLLECTION_CONFIRMED,
    HOME_COLLECTION_UNKNOWN_SLOT,
    HOME_COLLECTION_UNKNOWN_TEST,
    TEST_BOOKING_CANCELLED,
    TEST_BOOKING_CONFIRMED,
    TEST_BOOKING_UNKNOWN_CATEGORY,
    TEST_BOOKING_UNKNOWN_TEST,
    render_address_prompt,
    render_category_prompt,
    render_home_test_selection_prompt,
    render_morning_slot_prompt,
    render_test_confirmation_prompt,
    render_test_selection_prompt,
)

__all__ = [
    "CONSENT_ACCEPTED",
    "CONSENT_DECLINED",
    "CONSENT_PROMPT",
    "HOME_COLLECTION_CONFIRMED",
    "HOME_COLLECTION_UNKNOWN_SLOT",
    "HOME_COLLECTION_UNKNOWN_TEST",
    "TEST_BOOKING_CANCELLED",
    "TEST_BOOKING_CONFIRMED",
    "TEST_BOOKING_UNKNOWN_CATEGORY",
    "TEST_BOOKING_UNKNOWN_TEST",
    "render_address_prompt",
    "render_category_prompt",
    "render_home_test_selection_prompt",
    "render_morning_slot_prompt",
    "render_test_confirmation_prompt",
    "render_test_selection_prompt",
]
